{{- if .Values.argocd.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fireFlyArgoConfigMap" .}}
data:
  "crawler.json": {{ .Values.argocd.metadata | toJson | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fireFlyCollectorConfigMap" .}}
data:
{{ if .Values.apiEndpoint }}
  endpoint: {{ quote .Values.apiEndpoint }}
{{ end }}
{{ if .Values.loginEndpoint }}
  loginEndpoint: {{ quote .Values.loginEndpoint }}
{{ end }}
  collector.watchNamespace: default
  collector.ignoreNamespaces: |
    kube-system
  collector.overrideUniqueClusterId: {{ if .Values.overrideUniqueClusterId }}"true"{{ else }}"false"{{ end }}
  collector.resources: |
    {{ $resources := list "apiservices" "analysistemplates" "clusteranalysistemplates" "clusterroles" "clusterrolebindings" "configmaps" "controllerrevisions" "cronjobs" "csinodes" "customresourcedefinitions" "daemonsets" "deployments" "endpoints" "endpointslices" "flowschemas" "ingresses" "jobs" "leases" "namespaces" "networkpolicies" "nodes" "persistentvolumeclaims" "persistentvolumes" "pods" "priorityclasses" "prioritylevelconfigurations" "replicasets" "replicationcontrollers" "roles" "rolebindings" "rollouts" "rollouts/finalizers" "rollouts/status" "serviceaccounts" "services" "services/status" "statefulsets" "storageclasses" "poddisruptionbudgets" "podsecuritypolicies" "ingressclasses" "volumeattachments" "csidrivers" "validatingwebhookconfigurations" "mutatingwebhookconfigurations" "runtimeclasses" "horizontalpodautoscalers" }}
    {{- range $i, $name := $resources }}
      {{- if not (has $name $.Values.removeTypes) }}
      {{ $name -}}
      {{ end -}}
    {{ end -}}
    {{- range $i, $name := $.Values.addTypes }}
      {{ $name -}}
    {{ end -}}
    {{- if and ($.Values.collectSecrets) (not (has "secrets" $.Values.addTypes)) }}
      secrets
    {{ end -}}
