{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: Job
metadata:
  name: {{ template "fireFlyCollectorOnBoarderJob" . }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
spec:
  backoffLimit: 2
  template:
    metadata:
      name: "on-boarder"
    spec:
      restartPolicy: OnFailure
{{- if .Values.onBoarder.nodeSelector }}
      nodeSelector:
{{- toYaml .Values.onBoarder.nodeSelector | nindent 12 }}
{{- end }}
{{- if .Values.onBoarder.tolerations }}
      tolerations:
{{- toYaml .Values.onBoarder.tolerations | nindent 12 }}
{{- end }}
      containers:
        - name: integration-onboarding
          image: "{{ .Values.offBoarderImage.repository }}:{{ .Values.offBoarderImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fireFlyCredentialsSecret" . }}
                  key: accessKey
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fireFlyCredentialsSecret" . }}
                  key: secretKey
            - name: CLUSTER_ID
              value: {{ .Values.clusterId }}
            - name: APP_API_URL
              value: {{ .Values.appApiEndpoint }}
            - name: INTEGRATION_FLOW
              value: "ON_BOARD"
            - name: IS_PROD
              value: {{ if .Values.isProduction }}"true"{{ else }}"false"{{ end }}
