{{- if and (.Values.argocd.enabled) (not .Values.existingFireFlyArgocdCredentialsSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fireFlyArgocdCredentials" .}}
type: Opaque
data:
  IACATHON_ARGOCD_TOKEN: {{ .Values.argocd.token | b64enc }}
{{- end }}
{{- if not .Values.existingFireFlyCredentialsSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fireFlyCredentialsSecret" .}}
type: Opaque
data:
  accessKey: {{ .Values.accessKey | b64enc }}
  secretKey: {{ .Values.secretKey | b64enc }}
{{- end }}
