name: Build Collector integration-management Image
on:
  workflow_dispatch:
    inputs:
      collector-off-boarder-tag:
        description: 'Version Tag for the Collector Off-Boarder Docker Image'
        required: true
        default: '1.0.0'
  workflow_call:
    inputs:
      collector-off-boarder-tag:
        type: string
        description: 'Version Tag for the Collector Off-Boarder Docker Image'
        required: true
        default: '1.0.0'
    secrets:
      DOCKERHUB_USERNAME:
        description: 'Dockerhub Username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'Dockerhub Token'
        required: true
      SLACK_WEBHOOK:
        description: 'Slack Webhook'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Build and push image to prod
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: ./scripts/integration_management/
          file: ./scripts/integration_management/Dockerfile
          tags: |
            infralightio/k8-collector-offboarder:${{ (github.event.name == 'workflow_dispatch' && github.event.inputs.collector-off-boarder-tag) || inputs.collector-off-boarder-tag }}
            infralightio/k8-collector-offboarder:latest
          labels: |
            org.opencontainers.image.created=${{ steps.current-time.outputs.time }}
            org.opencontainers.image.authors=Infralight
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ (github.event.name == 'workflow_dispatch' && github.event.inputs.collector-off-boarder-tag) || inputs.collector-off-boarder-tag }}

      - name: Slack Notification
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://assets-global.website-files.com/5d514fd9493b0575f03520bd/5d8e0b39fd776a3c238e8753_icons8_infinity_large_filled_2.svg
          SLACK_MESSAGE: "K8s Collector Off Boarder image pushed to infralightio/k8s-collector:${{ github.event.inputs.collector-off-boarder-tag }}"
          SLACK_TITLE: "K8s Collector Off Boarder image pushed to infralightio/k8s-collector:${{ github.event.inputs.collector-off-boarder-tag }}"
          SLACK_USERNAME: cicdBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}