name: Build K8s Collector Image
on:
  workflow_dispatch:
    inputs:
      collectortag:
        description: "Version Tag for the Collector Docker Image"
        required: true
        default: "1.0.0"
  workflow_call:
    inputs:
      collectortag:
        type: string
        description: "Version Tag for the Collector Docker Image"
        required: true
        default: "1.0.0"
    secrets:
      DOCKERHUB_USERNAME:
        description: "Dockerhub Username"
        required: true
      DOCKERHUB_TOKEN:
        description: "Dockerhub Token"
        required: true
      SLACK_WEBHOOK:
        description: "Slack Webhook"
        required: true
      ACCESS_TOKEN_USR:
        description: "Github Access usr"
        required: true
      ACCESS_TOKEN_PWD:
        description: "Github Access pwd"
        required: true
      GLOBAL_PAT:
        description: "GLOBAL_PAT"
        required: true
jobs:
  build:
    runs-on: [self-hosted, production]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short commit hash
        uses: benjlevesque/short-sha@v3.0
        id: hash
        with:
          length: 8

      - name: Build and push multi-platform image
        run: |
          docker buildx create --use
          docker buildx inspect default --bootstrap
          docker buildx build \
            --progress=plain \
            --platform=linux/amd64,linux/arm64 \
            -t infralightio/k8s-collector:${{ github.event.inputs.collectortag }} \
            --label "org.opencontainers.image.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            --label "org.opencontainers.image.authors=Infralight" \
            --label "org.opencontainers.image.revision=${{ github.sha }}" \
            --label "org.opencontainers.image.version=${{ github.event.inputs.collectortag }}" \
            --build-arg "ACCESS_TOKEN_USR=${{ secrets.ACCESS_TOKEN_USR }}" \
            --build-arg "ACCESS_TOKEN_PWD=${{ secrets.ACCESS_TOKEN_PWD }}" \
            --build-arg "VERSION=${{ github.event.inputs.collectortag }}" \
            --build-arg "COMMIT_HASH=${{ steps.hash.outputs.sha }}" \
            --push .
        env:
          DOCKER_CLI_AGGREGATE: 1
          GOPRIVATE: "github.com/infralight/*,github.com/gofireflyio/*"

      - name: Slack Notification
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://assets-global.website-files.com/5d514fd9493b0575f03520bd/5d8e0b39fd776a3c238e8753_icons8_infinity_large_filled_2.svg
          SLACK_MESSAGE: "K8s Collector image pushed to infralightio/k8s-collector:${{ github.event.inputs.collectortag }}"
          SLACK_TITLE: "K8s Collector image pushed to infralightio/k8s-collector:${{ github.event.inputs.collectortag }}"
          SLACK_USERNAME: cicdBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
